#!/usr/bin/env bash

# If you are adding custom stuff under '${MSH}/modules'
# you can add new content here accordingly.

####
# Variables
##

# Core
MSH="${HOME}/.msh"
MSH_LIB="${MSH}/lib"
MSH_LIB_MODULES="${MSH_LIB}/modules"
MSH_MODULES="${MSH}/modules"
MSH_TOOLS="${MSH}/tools"
MSH_TEMPLATES="${MSH_TOOLS}/templates"

# Modules
MSH_ALIASES="${MSH_MODULES}/aliases"
MSH_COMPLETIONS="${MSH_MODULES}/completions"
MSH_PLUGINS="${MSH_MODULES}/plugins"
MSH_PROFILES="${MSH_MODULES}/profiles"
MSH_THEMES="${MSH_MODULES}/themes"
MSH_THEME="sexy"

# Load basic elements of MSH
source ${MSH_LIB}/assets.bash
source ${MSH_LIB}/shell.bash

# Load the shell theme, if enabled
[[ ${MSH_THEME} ]] && \
source "${MSH_THEMES}/${MSH_THEME}/${MSH_THEME}.theme.sh"


####
# Aliases
##

aliases=(
ansible
docker
general
git
grep
kubectl
ls
networking
pacman
systemd
terraform
tmux
)

# Inject active aliases into our shell
source ${MSH_LIB_MODULES}/aliases.bash


####
# Completions
##

completions=(
docker
github
makefile
ssh
)

# Inject active completions into our shell
source ${MSH_LIB_MODULES}/completions.bash


####
# Plugins
##

plugins=(
alias-completion
ansible
progress
)

# Inject active plugins into our shell
source ${MSH_LIB_MODULES}/plugins.bash


####
# Profiles
##

profiles=(
default
)

# Load active profiles
source ${MSH_LIB_MODULES}/profiles.bash
